app:
  name: "file-processing-api"
  version: "0.0.1"

grpc:
  port: 50052
  timeout: 30

logger:
  level: "debug"

postgres:
  pg_user: "user"
  pg_password: "myAwEsOm3pa55@w0rd"
  pg_host: "localhost"
  pg_port: 5432
  pg_db_name: "db"
  db_max_connections: 2
  db_connection_timeout: 30s

token:
  token_secret: "your-secret-key-here"
  accessTTL: 15m      # 15 minutes
  refreshTTL: 168h    # 1 week

migrations:
  path: "./migrations"